services:
  namenode:
    image: hadoop-namenode
    build: ./namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: hadoop-datanode
    build: ./datanode
    container_name: datanode-1
    restart: always
    volumes:
      - hadoop_datanode-1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    
  datanode2:
    image: hadoop-datanode
    build: ./datanode
    container_name: datanode-2
    restart: always
    volumes:
      - hadoop_datanode-2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode3:
    image: hadoop-datanode
    build: ./datanode
    container_name: datanode-3
    restart: always
    volumes:
      - hadoop_datanode-3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: hadoop-resourcemanager
    build: ./resourcemanager
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: hadoop-nodemanager
    build: ./nodemanager
    container_name: nodemanager-1
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  nodemanager2:
    image: hadoop-nodemanager
    build: ./nodemanager
    container_name: nodemanager-2
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  nodemanager3:
    image: hadoop-nodemanager
    build: ./nodemanager
    container_name: nodemanager-3
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: hadoop-historyserver
    build: ./historyserver
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  # hive-server:
  #   image: hive
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   environment:
  #     HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
  #     SERVICE_PRECONDITION: "hive-metastore:9083"
  #   ports:
  #     - "10000:10000"
  # hive-metastore:
  #   image: hive
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   command: /opt/hive/bin/hive --service metastore
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088 hive-metastore-postgresql:5432"
  #   ports:
  #     - "9083:9083"
  # hive-metastore-postgresql:
  #   image: hive-metastore
 
  
volumes:
  hadoop_namenode:
  hadoop_datanode-1:
  hadoop_datanode-2:
  hadoop_datanode-3:
  hadoop_historyserver:
